# Variáveis
CC = gcc
SERVER_TCP_SRC = serverTCP.c
CLIENT_TCP_SRC = clientTCP.c
SERVER_UDP_SRC = serverUDP.c
CLIENT_UDP_SRC = clientUDP.c

SERVER_TCP_OUT = serverTCP
CLIENT_TCP_OUT = clientTCP
SERVER_UDP_OUT = serverUDP
CLIENT_UDP_OUT = clientUDP

all: $(SERVER_TCP_OUT) $(CLIENT_TCP_OUT) $(SERVER_UDP_OUT) $(CLIENT_UDP_OUT)

$(SERVER_TCP_OUT): $(SERVER_TCP_SRC)
	$(CC) $(SERVER_TCP_SRC) -o $(SERVER_TCP_OUT)

$(SERVER_UDP_OUT): $(SERVER_UDP_SRC)
	$(CC) $(SERVER_UDP_SRC) -o $(SERVER_UDP_OUT)


$(CLIENT_TCP_OUT): $(CLIENT_TCP_SRC)
	$(CC) $(CLIENT_TCP_SRC) -o $(CLIENT_TCP_OUT)

$(CLIENT_UDP_OUT): $(CLIENT_UDP_SRC)
	$(CC) $(CLIENT_UDP_SRC) -o $(CLIENT_UDP_OUT)

clean:
	rm -f $(SERVER_TCP_OUT) $(CLIENT_TCP_OUT) $(SERVER_UDP_OUT) $(CLIENT_UDP_OUT)

